name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt
          pip install -r requirements.txt
          pip install -e .

      - name: Lint
        run: |
          prospector  --with-tool mypy  --profile prospector.yaml
          black --check telco_churn
          black --check tests

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests/unit

      - name: Deploy integration test
        run: |
          dbx deploy --jobs=db4ml-e2e-mlops-integration-test --files-only

      - name: Run integration test
        run: |
          dbx launch --job=db4ml-e2e-mlops-integration-test --as-run-submit --trace


